// A simple service to manage and play sound effects.

type SoundName = 'powerUp' | 'click' | 'sendMessage' | 'receiveMessage' | 'error' | 'play' | 'eat' | 'tiredSigh' | 'sleep';

// Pre-generated, simple synth sounds as Base64 Data URIs to avoid external assets.
const sounds: Record<SoundName, string> = {
    powerUp: 'data:audio/wav;base64,UklGRjwBAABXQVZFZm10IBAAAAABAAIARKwAABCxAgAEABAAZGF0YRgABAIAAQBE9/f3/v7/AP7+//v6/QAA//78/Pv5+gAA/v76+fn6+gAA/Pz7+fj4+AAAAAAA/v39/v7/AAAAAAAEAAAAAAAAAAAAAAAABAYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8=',
    click: 'data:audio/wav;base64,UklGRiIAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQAAAAAAAC/AAAB/gA=',
    sendMessage: 'data:audio/wav;base64,UklGRkIAAABXQVZFZm10IBAAAAABAAIARKwAABCxAgAEABAAZGF0YSAAAAAAAAD3/v3+AP8A/gD9AP79/f/+/gABAQECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/w==',
    receiveMessage: 'data:audio/wav;base64,UklGRkQBAABXQVZFZm10IBAAAAABAAIARKwAABCxAgAEABAAZGF0YTwAAAAA/v7/AAAAAAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AGIAdwB4AHkAegB7AHwAfQB+AH8AgACCAIMAhACFAIYAhwCIAIkAigCLAIwAjQCOAI8AkACRAJIAlACVAJYAlwCYAJsAnACdAJ4AnwCgAKAAogCiAKMApACmAKgAqQCqAKsArACtAK4ArwCwALEAsgCzALQAtQC2ALcAuAC5ALYAuwC8AL0AvgC/AMAAwQDCAMQAxQDGAMcAyADJAMoAywDMANMA1ADXANgA2QDaANsA3ADdAN4A3wDgAOEA4gDjAOUA5gDnAOgA6QDrAOwA7QDvAPAA8QDyAPMA9AD1APYA9wD4APkA+gD7APwA/QD+AP8A',
    error: 'data:audio/wav;base64,UklGRlABAABXQVZFZm10IBAAAAABAAIARKwAABCxAgAEABAAZGF0YTgAAAAA/v7/AP4A/AD8APoA+QD5APgA+AD3APYA9ADzAPIA8QDwAO8A7gDtAOsA6gDpAOYA5ADjAOIA4QDeANsA2gDXANQA0gDJAI4AigB+AHgAdgBvAGgAZQBiAF0AWQBUAE8ASgBEAD4AOQA0AC8AKgAlACAAFgAQAAoABgACAAMA/v/+APz//v/8AP7//gABAAAAAP78/v/8/gAAAAAAAPz9/f/+/v8AAAAAAAAA/v39/v7/AAAAAAADAAAAAAAAAAAAAAAABAYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8=',
    play: 'data:audio/wav;base64,UklGRkgBAABXQVZFZm10IBAAAAABAAIARKwAABCxAgAEABAAZGF0YTAAAAAA/v7/AAAAAAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AGIAdwB4AHkAegB7AHwAfQB+AH8AgACCAIMAhACFAIYAhwCIAIkAigCLAIwAjQCOAI8AkACRAJIAlACVAJYAlwCYAJsAnACdAJ4AnwCgAKAAogCiAKMApACmAKgAqQCqAKsArACtAK4ArwCwALEAsgCzALQAtQC2ALcAuAC5ALYAuwC8AL0AvgC/AMAAwQDCAMQAxQDGAMcAyADJAMoAywDMANMA1ADXANgA2QDaANsA3ADdAN4A3wDgAOEA4gDjAOUA5gDnAOgA6QDrAOwA7QDvAPAA8QDyAPMA9AD1APYA9wD4APkA+gD7APwA/QD+AP8A',
    eat: 'data:audio/wav;base64,UklGRkQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAAAAAA////AgACAAEAAQABAAAAAP8A/wD//P/9//7+/v38/Pn49/Xz8O/r6Ofm4uHg3tzb2tXU0s/Ny8jFxL++u7q0s6+uqaWhnZ2dmJiYlpaVlJOTjo2Mi4eGhISEgH58e3h2cXFtamtpaWdmZWVjY11cW1ZUU09OTktJR0ZFRENCQUA/PDs5ODc1NDMyMTAuLSwqKCcmJiQiHyAcFhQUEhEPDAoJBwUDAQAA',
    tiredSigh: 'data:audio/wav;base64,UklGRkIAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAAAAAA/v/9/v79/Pz6+ff29PPx7uns6Orn5eLh3t3c2drY1dXU09LSzs3My8rJxcTDwMC/vbu6t7Sysq+tq6ipqaempJ+enZ2dmZqZmJeWlZSUk5OTkI+OjYyLi4qJiIiGhoaFgH9/fXt5eXh3d3Z2dHFxcW5ubW1pZ2dnaGdnZmZlY2NjY2JgX19fXV1dXVxbW1pZVVVUU1NTT09PTktLTEtKSUpJR0dGRkVDQ0JCQUA/Pz49PTs7Ojk5ODg3NzY2NTU0NDMyMjExMC8vLi0sLCsrKSkoJyYmJSQjIiEgHx4dHBsaGRgXFhUUExIREA8OCwsKCQgHBgUEAwIBAAD//w==',
    sleep: 'data:audio/wav;base64,UklGRkAAAABXQVZFZm10IBAAAAABAAIARKwAABCxAgAEABAAZGF0YSAAAAAA/v7/AP4A/AD8APoA+QD5APgA+AD3APYA9ADzAPIA8QDwAO8A7gDtAOsA6gDpAOYA5ADjAOIA4QDeANsA2gDXANQA0gDJAI4AigB+AHgAdgBvAGgAZQBiAF0AWQBUAE8ASgBEAD4AOQA0AC8AKgAlACAAFgAQAAoABgACAP7//gD8//7//AD+///+/v/8/v/+/gAAAAAAAPz9/f/+/v8AAAAAAAAA/v39/v7/AAAAAAADAAAAAAAAAAAAAAAABAYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8=',
};

let audioContext: AudioContext | null = null;

const getAudioContext = () => {
  if (!audioContext) {
    if (typeof window !== 'undefined') {
      audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
    }
  }
  return audioContext;
};

export const playSound = (name: SoundName) => {
    const context = getAudioContext();
    if (!context) return;

    if (context.state === 'suspended') {
        context.resume();
    }
    const audio = new Audio(sounds[name]);
    audio.play().catch(e => console.error(`Error playing sound "${name}":`, e));
};